services:
  - type: web
    name: chat-backend
    env: node
    buildCommand: ./.renderbuild.sh
    startCommand: yarn workspace Backend start
    branch: main
    repo: https://github.com/mayur777-ui/Web-chat-app
    rootDir: .
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_EMAIL
        sync: false
      - key: GOOGLE_EMAIL_PASS
        sync: false
      - key: MONGO_PASSWORD
        sync: false

  - type: web
    name: chat-frontend
    env: static
    buildCommand: ./.renderbuild.sh
    staticPublishPath: Frontend/dist
    branch: main
    repo: https://github.com/mayur777-ui/Web-chat-app
    rootDir: .